### ISSUE TITLE
good until second last part of step 4

### ISSUE THREAD

**Issue by tBalwithatouchofMalice** [JoeWDavies/geoblender#10]
There is no 'adaptive subdivision' to tick off.

Up to that step, I am good:

<img width="2048" alt="Screen Shot 2022-04-04 at 3 45 18 PM" src="https://user-images.githubusercontent.com/78912736/161606717-72ce6d10-40a5-4e3a-9c81-6514c41479cf.png">

Then I add the Subdivision:

<img width="348" alt="Screen Shot 2022-04-04 at 3 45 55 PM" src="https://user-images.githubusercontent.com/78912736/161606800-6fc60c57-d101-44b8-963c-1ff21d73ac36.png">

Then my render starts out like this:

<img width="2047" alt="Screen Shot 2022-04-04 at 3 46 28 PM" src="https://user-images.githubusercontent.com/78912736/161606874-ae3b0fb7-ee3b-4064-a762-b32ce5370690.png">

Final render with the subdivision added:

<img width="810" alt="Screen Shot 2022-04-04 at 3 50 51 PM" src="https://user-images.githubusercontent.com/78912736/161607081-1abb664e-542e-43cf-8752-e8d1bb771a38.png">

Any tips?

For the record, I am just looking to do the large island itself.  I was just going to hack off the mainland and extra ocean in the final image.
I can share my .tif file with you as well, if you like.

**Comment by jonnyirving** [comment]
I think you might be missing the 'Adaptive subdivision' option because you didn't switch the rendering "Feature set" to experimental. Run through the step running up to this bullet point again and see how you get on:
> In the same tab, we must also set the render engine to 'cycles' and set 'feature set' to experimental. This enables blender to do its shaded-relief magic. If you have a powerful graphics card I reccommend chaning the 'device' to 'GPU compute' - that way renders will be much faster.

To be fair the screenshot doesn't match the text too well so it's a bit confusing.

**Comment by JoeWDavies** [comment]
@jonnyirving Thanks for pointing out the inconsistency with the screenshot. I have updated the screenshot!
