### ISSUE TITLE
Not sure where to start - complete beginner

### ISSUE THREAD

**Issue by Tjobbe** [JoeWDavies/geoblender#11]
As the title says.

I've never used QGIS before, and have only used blender to create 3d models for my 3d printer, so please go easy on me.

I do really appreciate the time you've put into this tutorials, but if you could fill in some sizeable gaps for me, or point me in the right direction, that would be great.

I've downloaded the data files for my target area. I have two kml files and a tif file. Not sure which I need to import into QGIS for starters, or even how. I think that knowing how to do this fundamental first step would help me massively to begin with.

I also don't know how to create a polygon for the desired area, in my case, Gloucestershire, England.

Thanks for any pointers, I appreciate that this may be beyond my skillset, but I'd like to try.

**Comment by jonnyirving** [comment]
I'm in a similar boat, I've got the `kml` file but I can see that GGIS only allows me to open `.qgs` or `.qgz` files.

**Comment by JoeWDavies** [comment]
You can probably find a polygon of Gloucestershire on Natural Earth: https://www.naturalearthdata.com/downloads/10m-cultural-vectors/

In QGIS you can just drag and drop suitable files onto the map. My advice is to use geopackage or shapefile for the vector boundaries and tif for your DEM.
