### ISSUE TITLE
cannot get the bump and displacement setting to work

### ISSUE THREAD

**Issue by mav3r1ck1981** [joewdavies/geoblender#17]
Hi Joe, hoping you might be able to help. Ive followed your excellent tutorial, and it works perfectly for me until the latter half of section 4. 

![image](https://github.com/joewdavies/geoblender/assets/61555547/8c40c870-e37c-4b13-9c42-a2c1dd104261)

i get the this section and add the subdivision surface modifier, i change the setting to bump and displacement and i press F12 to render the new image, and this is what happens:

![image](https://github.com/joewdavies/geoblender/assets/61555547/989730d2-f6fd-48bb-aa4b-0a473156e70f)

Do you have any ideas what im doing wrong? im using Blender 3.6.2, and ive downloaded your example blend file, and mirrored your setting exactly.

Thanks in advance,

Paul

**Comment by joewdavies** [comment]
hmmm could you share some screenshots of your shader nodes setup and of your modifiers?
