### ISSUE TITLE
Can't get adaptive subdivision to work

### ISSUE THREAD

**Issue by MoritzStefaner** [JoeWDavies/geoblender#2]
Hi,

thanks for the great tutorial!
I got everything to work, but my renders still look pretty "flat" — see attached sample render:
<img width="1329" alt="Screenshot 2021-09-20 at 21 55 06" src="https://user-images.githubusercontent.com/216044/134066853-7d3af9c9-caa8-48f5-8f06-f2830f46ef9d.png">

I think the adaptive subdivision has no effect. Any ideas?

<img width="229" alt="Screenshot 2021-09-20 at 21 58 52" src="https://user-images.githubusercontent.com/216044/134067018-418b2692-1ec2-4cd0-9f4d-c8cef60d295c.png">
<img width="406" alt="Screenshot 2021-09-20 at 21 59 08" src="https://user-images.githubusercontent.com/216044/134067051-36fd0b55-80b3-4443-aea1-f4a561eee24a.png">

**Comment by JoeWDavies** [comment]
Hmm..

Does increasing the scale value in the displacement node have any effect? 

![image](https://user-images.githubusercontent.com/25485293/134141315-a725262a-b8c1-4e22-828f-f56daed473c3.png)

If not, you could share the .blend file and I could take a look

**Comment by JoeWDavies** [comment]
I think I found the issue!

With the plane selected, go into material properties > settings > surface and under displacement select 'displacement and bump'

![image](https://user-images.githubusercontent.com/25485293/134147044-32f323b7-d46f-4f00-8bc8-55e37e981bc3.png)

I must have missed this step in my tutorial! 

Let me know if that does the trick,

thanks for helping me improve it :)

**Comment by MoritzStefaner** [comment]
Yes, that's it! 😍
<img width="546" alt="Screenshot 2021-09-21 at 11 44 59" src="https://user-images.githubusercontent.com/216044/134149374-ad90ba5c-f57b-4314-a797-c3c32f564d56.png">

**Comment by JoeWDavies** [comment]
Noice!

P.S. If you want to prevent coastal areas from looking 'flooded' you can follow the extra step in the tutorial by creating a mask using polygons for France and Italy (if you don't have them you can use [natural earth data](https://naturalearth.s3.amazonaws.com/10m_cultural/ne_10m_admin_0_countries.zip) - in QGIS select France and Italy then export > save selected features)

All the best,
Joe

**Comment by MoritzStefaner** [comment]
Wonderful, thanks! This is a lot of fun :)
