### ISSUE TITLE
Normalization for input pixel values for TIF

### ISSUE THREAD

**Issue by stalker314314** [JoeWDavies/geoblender#4]
Hi,
First of all, thanks for making this. I am Linux user for 20 years, but I stayed away from "complicated" Blender. But, as an avid OSM user, you just gave me reason to open Blender for first time determined to make something!

Issue: Once I add "subdivision surface", I got very weird behavior. As if whole plane is protruded heavily, spikes everywhere[1]. I think it is related to the fact that Blender uses meters (right?) and that TIF also outputs meters, in my case 0-2500m. However, I think your TIF must be outputting 0.0-1.0 or something small? I *think* I solved my problem (I think?) by adding some normalization to 0.0-1.0 range, as in picture[1]. However, first I am not sure if this is my problem only, or there is some step missing from your tutorial, so I wanted to sync with you. What do you think?

[1]
![slika](https://user-images.githubusercontent.com/188751/136285130-e7efec81-8d7f-470e-b61d-dab518a106d0.png)

[2]
![slika](https://user-images.githubusercontent.com/188751/136284134-fb617cc4-71e1-4f9d-9662-ddb88612bbc1.png)

**Comment by JoeWDavies** [comment]
In that case it's a problem with your TIF. Did you export it from QGIS as a rendered image?

**Comment by stalker314314** [comment]
OK, that was a problem. I just exported it as TIF:( (I thought I know that, first part of tutorial and skipped it:D) I will close this issue, thanks for helping!
