### ISSUE TITLE
Clip raster by mask layer

### ISSUE THREAD

**Issue by MarkoWeide** [JoeWDavies/geoblender#5]
Hi, thanks for the great tutorial! When I try to clip the DEM to a specific area I get an error. What am I doing wrong?
![screenshot](https://user-images.githubusercontent.com/92266906/137321220-0e31dc4d-77ce-49fe-9dc3-bf49913ce51e.png)

**Comment by JoeWDavies** [comment]
QGIS cannot find your shapefile... I normally just drag and drop it into QGIS and then it will automatically appear in the dropdown

**Comment by spudulike97** [comment]
Hi, I run into the same error as @MarkoWeide when I attempt to use the file in clip raster by mask layer. And when I try dragging and dropping the file into QGIS as you suggest I get this error: 
<img width="437" alt="image" src="https://user-images.githubusercontent.com/95236471/143899252-54c52d29-6b3e-41d1-aa7d-01112f626994.png">
Any ideas how I can solve this?

**Comment by tydonk** [comment]
From some research into QGIS is appears a shapefile is more than just .shp, it also needs a .shx and .dbf - https://en.wikipedia.org/wiki/Shapefile
