### ISSUE TITLE
Raising the mask

### ISSUE THREAD

**Issue by dinojah** [JoeWDavies/geoblender#6]
So I have a problem about the last tip - raising the map as you did for Greece. 

Please check my node, I think I have done everything as you said, but still don't get that effect. 
![question](https://user-images.githubusercontent.com/48015881/140654801-adc5db76-8157-4808-b358-f6a409cc6248.PNG)

**Comment by JoeWDavies** [comment]
I said: *use a 'math' node connected to the DEM as the color1 input of a 'mix' node and color2 as the DEM, then use the mask as the Fac of the mix node. The result of this mix node is then plugged into the displacement node.*

You are plugging the mix node into the principled BSDF, not into the displacement node as i said.
