### ISSUE TITLE
Masking the sea using the gradient

### ISSUE THREAD

**Issue by laem** [JoeWDavies/geoblender#8]
Hi, thanks a lot for this awesome tutorial. 

Regarding the last section, [extra mask for aoi](https://github.com/joewdavies/geoblender#extra-mask-for-aoi-).

I found that a cheap way to put appart the sea from the land is to add a left color to the gradient, very low, 0.011 in my case. 

![image](https://user-images.githubusercontent.com/1177762/149553594-2071032c-cf38-4e11-a64e-9f769107e2ba.png)

Looks fine :) 

![image](https://user-images.githubusercontent.com/1177762/149553656-1dee882e-dcd3-4ae2-8789-dc0bedd84a36.png)

**Comment by laem** [comment]
Also, I found this site really cool to get the boundary shape : http://polygons.openstreetmap.fr/index.py

**Comment by JoeWDavies** [comment]
Hi! Yes, but be careful as you will often flood coastal areas by doing this. I have often found that not even 0.00000001 is capable of differentiating between land and sea, which is why I recommend using a mask.
