### ISSUE TITLE
Raising the AOI from the background

### ISSUE THREAD

**Issue by iikkamovitsh** [JoeWDavies/geoblender#9]
Hi Joe,
Great tutorial and super fun to create a map. I've been succeeding in all of the other steps but the last tip is just not working out for me. 

To best of my abilities (with zero previous experience in Blender) I tried to raise the AOI from the background. I have created the path as shown below but it just doesn't work. I am also a bit confused should I add a new mix node where the math node is connected or should I use what is created earlier.

![image](https://user-images.githubusercontent.com/24233891/151661057-3584ae1d-445d-4208-a0e1-779941bfb471.png)
 

Any tips you could share - maybe even a blender file or a screenshot of your settings?

Also, is the camera angle changed for this last step or only adding math node and related things?

Edit: This is the render that comes out with the settings used
![image](https://user-images.githubusercontent.com/24233891/151661475-ffd81ed4-5337-4a51-a0d3-d88d2a87ac52.png)

Cheers!

**Comment by ryepenchi** [comment]
Hi iikkamovitsh,

this is a setup that has worked for me to add a fixed displacement value within the area of interest. To actually see the effects I suggest playing with the camera position. 

![grafik](https://user-images.githubusercontent.com/73063344/151826232-45aee142-331f-447a-a7f4-45e34cc7a11f.png)

Also having a look at the other linked tutorial [somethingaboutmaps](https://somethingaboutmaps.wordpress.com/blender-relief-tutorial-final-adjustments/) had some additional nice tweaks in store.
